#!/bin/bash

set -e
set -u

function teardown {
    echo "Running teardown"
    kill "$stack_pid"
}

trap teardown SIGHUP SIGINT SIGTERM ERR

echo "Starting level-ip"
echo
./lvl-ip &
stack_pid=$!

echo "Running tests, resting awhile.."
echo 
sleep 5

ping -c1 10.0.0.4

echo

arping -c1 -I tap0 10.0.0.4

echo

echo "Killing level-ip"
kill $stack_pid
