#!/bin/bash


PYTHON="python2.7"
UTSCAPY="venv/lib/python2.7/site-packages/scapy/tools/UTscapy.py"

function cleanup {
    kill "$stack_pid"
}

trap cleanup EXIT ERR

../lvl-ip 1>/dev/null &
stack_pid="$!"

sleep 3

"$PYTHON" "$UTSCAPY" "$@"
