#!/bin/bash

set -eu

source "$(dirname $0)/../../utils/common"
# Simple end-to-end test for an application's curl

function strip_http_header {
    sed 's/^Date:.*/Date:/' | sed 's/^Server:.*/Server:/'
}

function setup {
    start_stack

    /usr/bin/env python2.7 -m SimpleHTTPServer >/dev/null 2>&1 &
    httpserver="$!"

    sleep 1

    tc qdisc add dev tap0 root netem duplicate 50%
}

function teardown {
    kill "$stackip"
    kill "$httpserver"
}

function test_normal_http_get {
    response="$("$repo/tools/level-ip" "$repo/apps/curl/curl" 10.0.0.5 8000 | strip_http_header)"

    diff "$folder/curl-fixture.txt" <(echo "$response")
}

setup
trap teardown EXIT ERR

test_run "test_normal_http_get"
