#!/bin/bash

set -eu

repo="$(git rev-parse --show-toplevel)"
folder="$(dirname $0)"

function start_stack {
    "$repo/lvl-ip" >/dev/null &
    stackip="$!"

    sleep 3
}

function test_pass {
    echo -e "\t Test pass: $1"
}

function test_fail {
    echo -e "\tTest fail: $1" 2>&1
    exit 1
}

function test_run {
    eval "$1" || test_fail "$1"

    test_pass "$1"
}
